[fix] delta time
appa-labs/Achilles pull request #5
Opened 2024-03-09 17:58 UTC by WhyNovaa

2024-03-09 18:07 UTC, DedalusMoonlight commented on src/main.cpp
удали либу <chrono>, получается она уже не нужна, удали метку start и перенеси sf::Time dt в самое начало цикла, как и 51 строчку (engine.frametime = ... ). Ну и еще может имя для таймера повыразительней, например timer - почему нет

2024-03-09 18:11 UTC, DedalusMoonlight requested changes
удали либу , получается она уже не нужна, удали метку start и перенеси sf::Time dt в самое начало цикла, как и 51 строчку (engine.frametime = ... ). Ну и еще может имя для таймера повыразительней, например timer - почему нет

2024-03-09 18:21 UTC, DedalusMoonlight approved these changes
отлично, спасибо

2024-03-10 05:36 UTC, kirillpyasecky approved these changes
Good job

2024-03-10 05:36 UTC, merged